name: Deploy to Moodle
on:
  push:	
    branches:	
      - main

jobs:
  deploy:
    name: Deploy to Moodle
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy
      uses: s0/git-publish-subdir-action@v2.4.0
      env:
        REPO: self
        BRANCH: site
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
