name: Priting file names

on: 
  push:
    branch: [main]

jobs:
  info:
    name: Print Info
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Present working directory
      run: pwd
    - name: Files
      run: ls
    - name: show content
      run: cat intro.md
    - name: change directory
      run: cd build
